import { useEffect, useMemo } from "react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import { track } from "../lib/track.js";
import { decodeResult } from "../lib/encodeResult.js";
import { getStage } from "../lib/stages.js";
import ShareButton from "./ShareButton.jsx";
import SiteHeader from "./SiteHeader.jsx";

// Pre-offer results, shared by the Applying and Interviewing stages. Mirrors
// ResultsPage's visual language and stateless ?d= encoding, but the
// researched range is the hero rather than a score.

const money = (n) =>
  typeof n === "number" && Number.isFinite(n)
    ? `$${Math.round(n).toLocaleString("en-US")}`
    : "—";

const CONFIDENCE_COPY = {
  high: "High confidence — multiple quality sources agreed on this market.",
  medium: "Medium confidence — the data was thinner than we'd like.",
  low: "Low confidence — this leans on adjacent roles or a broader market.",
};

export default function ApplyResultsPage({ flow = "apply" }) {
  const [searchParams] = useSearchParams();
  const encoded = searchParams.get("d");
  const stage = getStage(flow);

  const data = useMemo(() => {
    if (!encoded) return null;
    try {
      return decodeResult(encoded);
    } catch {
      return null;
    }
  }, [encoded]);

  // Guarded inside the effect rather than wrapped in a condition, so the hook
  // order stays stable across the no-data early return below.
  useEffect(() => {
    if (data?.analysis) {
      track("results_viewed");
    }
  }, [data]);

  if (!data) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-navy-50 px-6">
        <div className="text-center">
          <p className="text-lg font-medium text-navy-900 mb-2">
            We couldn't load this result.
          </p>
          <p className="text-slate-600 mb-6">
            The link may be broken or incomplete.
          </p>
          <Link
            to="/"
            className="inline-block bg-navy-900 text-white rounded-md px-5 py-2.5 font-medium hover:bg-navy-600 transition"
          >
            Start Over
          </Link>
        </div>
      </div>
    );
  }

  const { form, analysis } = data;

  return (
    <div className="min-h-screen bg-navy-50">
      <SiteHeader />
      <header>
        <div className="max-w-3xl mx-auto px-6 pt-10 pb-2">
          <h1 className="text-3xl sm:text-4xl font-serif font-semibold text-navy-950">
            Your Target Range
          </h1>
          <p className="text-slate-700 mt-4">
            {form.targetRole}
            {form.targetCompany ? ` at ${form.targetCompany}` : ""} ·{" "}
            {form.location} · {form.yearsExperience} years
          </p>
          <p className="text-navy-800 mt-4 font-medium max-w-xl">
            Negotiation doesn't start at the offer. It starts the moment a
            recruiter asks what you make.
          </p>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-8 space-y-8">
        <div className="flex flex-wrap items-center justify-between gap-4">
          <ShareButton />
          <Link
            to={stage.basePath}
            className="inline-block py-2.5 text-sm font-medium text-navy-700 hover:text-navy-900 transition"
          >
            ← Start over
          </Link>
        </div>

        <RangeCard analysis={analysis} />

        <SourceList sources={analysis.sources} />

        <Callout title="The biggest way you could undercut yourself">
          {analysis.biggest_risk}
        </Callout>

        <Callout title="Where you are right now" tone="light">
          {analysis.call_status_note}
        </Callout>

        {/* The three strategies are deliberately NOT shown here. They are
            effectively the script — the actual words to say — and giving them
            away free removes the reason to buy it. They stay in the analysis
            payload because the script generator builds from them. */}

        <NextStepChoice encoded={encoded} stage={stage} />

        <p className="text-center text-sm text-slate-500 -mt-4">
          Your range and strategy are generated by AI, guided by NLN's
          negotiation methodology, using market data researched at the time of
          your request.
        </p>
      </main>
    </div>
  );
}

// The hero. Handles the no-data case explicitly rather than rendering
// placeholder numbers that would look authoritative.
function RangeCard({ analysis }) {
  const range = analysis.market_range;

  if (!range?.base) {
    return (
      <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-6 sm:p-8">
        <h2 className="text-lg font-serif font-semibold text-navy-900 mb-2">
          We couldn't verify a market range for this role
        </h2>
        <p className="text-slate-700">{analysis.range_rationale}</p>
        <p className="text-sm text-slate-500 mt-4">
          Rather than show you a number we can't stand behind, we've left this
          open. Everything below still applies, and your script will include
          instructions for building a range from your own research.
        </p>
      </div>
    );
  }

  return (
    <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-6 sm:p-8">
      <RangeRow label="Base salary" points={range.base} featured />
      {range.total_comp && (
        <div className="mt-6 pt-6 border-t border-slate-200">
          <RangeRow label="Total compensation" points={range.total_comp} />
        </div>
      )}

      <p className="text-slate-700 mt-6">{analysis.range_rationale}</p>

      <div className="mt-4 flex flex-wrap items-center gap-x-4 gap-y-1">
        <p className="text-xs text-slate-500">
          {CONFIDENCE_COPY[analysis.confidence] || ""}
        </p>
      </div>

      <p className="text-sm text-navy-800 mt-4 bg-navy-50 rounded-lg px-4 py-3">
        <span className="font-semibold">Your walk-away floor is{" "}
        {money(range.base.low)}.</span>{" "}
        Below that, the role isn't worth your time — and knowing that before
        the call is what keeps you from drifting down during it.
      </p>
    </div>
  );
}

function RangeRow({ label, points, featured }) {
  const cols = [
    ["Low", points.low],
    ["Target", points.target],
    ["Stretch", points.stretch],
  ];
  return (
    <div>
      <p className="text-xs font-semibold uppercase tracking-wide text-slate-500 mb-3">
        {label}
      </p>
      <div className="grid grid-cols-3 gap-1.5 sm:gap-3">
        {cols.map(([name, value], i) => (
          <div
            key={name}
            className={`rounded-lg px-0.5 py-4 sm:px-3 text-center ${
              i === 1
                ? "bg-navy-900 text-white"
                : "bg-navy-50 text-navy-900"
            }`}
          >
            {/* Six-figure numbers overflow a third of a 375px screen at the
                larger sizes, so the mobile step is set to fit "$456,000"
                rather than scaled down from desktop. */}
            <p
              className={`font-serif font-semibold whitespace-nowrap ${
                featured
                  ? "text-[15px] sm:text-xl md:text-2xl"
                  : "text-[15px] sm:text-lg md:text-xl"
              }`}
            >
              {money(value)}
            </p>
            <p
              className={`text-xs mt-1 ${
                i === 1 ? "text-navy-100" : "text-slate-600"
              }`}
            >
              {name}
            </p>
          </div>
        ))}
      </div>
    </div>
  );
}

function Callout({ title, children, tone = "dark" }) {
  if (!children) return null;
  if (tone === "light") {
    return (
      <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-6 sm:p-8">
        <h2 className="text-lg font-serif font-semibold text-navy-900 mb-2">
          {title}
        </h2>
        <p className="text-slate-700">{children}</p>
      </div>
    );
  }
  return (
    <div className="bg-navy-900 text-white rounded-xl p-6 sm:p-8">
      <p className="text-xs font-semibold uppercase tracking-wide text-navy-300 mb-2">
        {title}
      </p>
      <p className="text-lg">{children}</p>
    </div>
  );
}

// Market-data sources the range was built on. Empty when no usable data
// was found.
function SourceList({ sources }) {
  if (!Array.isArray(sources) || sources.length === 0) return null;

  return (
    <p className="text-sm text-slate-500 -mt-4">
      Market data sourced from{" "}
      {sources.map((s, i) => (
        <span key={`${s.url}-${i}`}>
          {i > 0 && (i === sources.length - 1 ? " and " : ", ")}
          <a
            href={s.url}
            target="_blank"
            rel="noopener noreferrer"
            title={s.note}
            className="font-medium text-navy-600 hover:text-navy-900 underline transition"
          >
            {s.name}
          </a>
        </span>
      ))}
      .
    </p>
  );
}

function NextStepChoice({ encoded, stage }) {
  const navigate = useNavigate();

  function handleGetScript() {
    track("script_cta_clicked");
    navigate(`${stage.basePath}/proof${encoded ? `?d=${encoded}` : ""}`);
  }

  function handleBookSession() {
    track("session_cta_clicked");
    navigate("/session");
  }

  return (
    <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-6 sm:p-8">
      <p className="font-serif font-semibold text-navy-900 text-xl text-center mb-6">
        What do you want next — a script you can run yourself, or a
        negotiator in your corner?
      </p>
      <div className="grid sm:grid-cols-2 gap-4">
        <button
          type="button"
          onClick={handleGetScript}
          className="rounded-lg bg-navy-900 hover:bg-navy-600 text-white p-5 text-center transition"
        >
          <span className="block font-semibold">Get my custom script</span>
          <span className="block text-sm text-navy-100 mt-1">
            Word-for-word answers for your recruiter screening call
          </span>
        </button>
        <button
          type="button"
          onClick={handleBookSession}
          className="rounded-lg border-2 border-navy-900 text-navy-900 hover:bg-navy-50 p-5 text-center transition"
        >
          <span className="block font-semibold">Book a Strategy Session</span>
          <span className="block text-sm text-slate-600 mt-1">
            Get a negotiator in your corner for the actual call
          </span>
        </button>
      </div>
    </div>
  );
}
