import { useEffect, useMemo } from "react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import { track } from "../lib/track.js";
import { decodeResult } from "../lib/encodeResult.js";
import { getFlow } from "../lib/flows.js";
import ShareButton from "./ShareButton.jsx";
import SiteHeader from "./SiteHeader.jsx";
import {
  BrokenResultNotice,
  Callout,
  NextStepChoice,
  RangeCard,
  SourceList,
} from "./RangeBlocks.jsx";

// Expecting-an-offer-soon results. Same building blocks as the screening-call
// results page, but the content is about the offer call: how to read the
// number when it lands, and the one rule that governs the whole conversation.

export default function OfferSoonResultsPage() {
  const [searchParams] = useSearchParams();
  const encoded = searchParams.get("d");
  const navigate = useNavigate();
  const stage = getFlow("offer_soon");

  const data = useMemo(() => {
    if (!encoded) return null;
    try {
      return decodeResult(encoded);
    } catch {
      return null;
    }
  }, [encoded]);

  // Guarded inside the effect rather than wrapped in a condition, so the hook
  // order stays stable across the no-data early return below.
  useEffect(() => {
    if (data?.analysis) {
      track("results_viewed");
    }
  }, [data]);

  if (!data) return <BrokenResultNotice />;

  const { form, analysis } = data;

  return (
    <div className="min-h-screen bg-navy-50">
      <SiteHeader />
      <header>
        <div className="max-w-3xl mx-auto px-6 pt-10 pb-2">
          <h1 className="text-3xl sm:text-4xl font-serif font-semibold text-navy-950">
            What a Strong Offer Looks Like
          </h1>
          <p className="text-slate-700 mt-4">
            {form.targetRole}
            {form.targetCompany ? ` at ${form.targetCompany}` : ""} ·{" "}
            {form.location} · {form.yearsExperience} years
          </p>
          <p className="text-navy-800 mt-4 font-medium max-w-xl">
            The worst thing you can do on the offer call is say yes, or say a
            number, on the spot. Here's what to do instead.
          </p>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-8 space-y-8">
        <div className="flex flex-wrap items-center justify-between gap-4">
          <ShareButton />
          <Link
            to={stage.basePath}
            className="inline-block py-2.5 text-sm font-medium text-navy-700 hover:text-navy-900 transition"
          >
            ← Start over
          </Link>
        </div>

        <RangeCard
          analysis={analysis}
          noDataNote="Rather than show you a number we can't stand behind, we've left this open. Everything below still applies, and your script will include instructions for building a range from your own research before the call."
          floorNote="An offer below that is a real gap worth addressing in your counter — and knowing the number before the call is what lets you recognize it instantly."
        />

        <Callout title="How to read the offer when you hear it" tone="light">
          {analysis.offer_benchmark_note}
        </Callout>

        {/* Static, not model-generated: this is the rule the whole flow
            exists to deliver, so it must never vary or be dropped. */}
        <div className="bg-navy-950 text-white rounded-xl p-6 sm:p-8">
          <p className="text-xs font-semibold uppercase tracking-wide text-navy-300 mb-2">
            Your one rule for the call
          </p>
          <p className="text-lg">
            Don't accept and don't counter on the spot. Appreciate it,
            understand it, and ask for time.
          </p>
        </div>

        <Callout title="The biggest way you could give away leverage">
          {analysis.biggest_risk}
        </Callout>

        <Callout title="Your leverage going into this call" tone="light">
          {analysis.leverage_read}
        </Callout>

        <Callout title="Where things stand on compensation" tone="light">
          {analysis.call_status_note}
        </Callout>

        <SourceList sources={analysis.sources} />

        {/* The three strategies are deliberately NOT shown here, same reason
            as the screening-call results page: they are effectively the
            script. They stay in the payload for the script generator. */}

        <NextStepChoice
          scriptBlurb="Word-for-word lines for the moment the number lands"
          onGetScript={() => {
            track("script_cta_clicked");
            navigate(`${stage.proofPath}${encoded ? `?d=${encoded}` : ""}`);
          }}
          onBookSession={() => {
            track("session_cta_clicked");
            navigate("/session");
          }}
        />

        <p className="text-center text-sm text-slate-500 -mt-4">
          Your range and strategy are generated by AI, guided by NLN's
          negotiation methodology, using market data researched at the time of
          your request.
        </p>
      </main>
    </div>
  );
}
