import { useEffect, useMemo } from "react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import { track } from "../lib/track.js";
import { decodeResult } from "../lib/encodeResult.js";
import ScoreCard from "./ScoreCard.jsx";
import OpportunityList from "./OpportunityList.jsx";
import StrategyCards from "./StrategyCards.jsx";
import ShareButton from "./ShareButton.jsx";
import SiteHeader from "./SiteHeader.jsx";

export default function ResultsPage() {
  const [searchParams] = useSearchParams();
  const encoded = searchParams.get("d");

  const data = useMemo(() => {
    if (!encoded) return null;
    try {
      return decodeResult(encoded);
    } catch {
      return null;
    }
  }, [encoded]);

  // Guarded inside the effect rather than wrapped in a condition, so the hook
  // order stays stable across the no-data early return below.
  useEffect(() => {
    if (data?.analysis) {
      track("results_viewed", { offerScore: data.analysis.offerScore });
    }
  }, [data]);

  if (!data) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-navy-50 px-6">
        <div className="text-center">
          <p className="text-lg font-medium text-navy-900 mb-2">
            We couldn't load this result.
          </p>
          <p className="text-slate-600 mb-6">
            The link may be broken or incomplete.
          </p>
          <Link
            to="/"
            className="inline-block bg-navy-900 text-white rounded-md px-5 py-2.5 font-medium hover:bg-navy-600 transition"
          >
            Analyze a New Offer
          </Link>
        </div>
      </div>
    );
  }

  const { form, analysis } = data;

  // The risk-tolerance answer picks the recommended strategy; older shared
  // links predate the question and fall back to Balanced.
  const recommendedKey =
    { Cautious: "conservative", Balanced: "balanced", Aggressive: "aggressive" }[
      form.riskTolerance
    ] || "balanced";

  return (
    <div className="min-h-screen bg-navy-50">
      <SiteHeader />
      <header>
        <div className="max-w-3xl mx-auto px-6 pt-10 pb-2">
          <h1 className="text-3xl sm:text-4xl font-serif font-semibold text-navy-950">
            Your Offer Analysis
          </h1>
          <p className="text-slate-700 mt-4">
            {form.role}
            {form.company ? ` at ${form.company}` : ""} · {form.location}
          </p>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-8 space-y-8">
        <div className="flex flex-wrap items-center justify-between gap-4">
          <ShareButton />
          <Link
            to="/"
            className="inline-block py-2.5 text-sm font-medium text-navy-700 hover:text-navy-900 transition"
          >
            ← Analyze another offer
          </Link>
        </div>

        <ScoreCard score={analysis.offerScore} interpretation={analysis.scoreInterpretation} />

        <SourceList sources={analysis.sources} />

        <OpportunityList opportunities={analysis.opportunities} />

        <StrategyCards
          strategies={analysis.strategies}
          recommendedKey={recommendedKey}
        />

        <div
          id="recommended-next-step"
          className="bg-navy-900 text-white rounded-xl p-6 sm:p-8 scroll-mt-6"
        >
          <p className="text-xs font-semibold uppercase tracking-wide text-navy-300 mb-2">
            Recommended Next Step
          </p>
          <p className="text-lg">{analysis.recommendedNextStep}</p>
        </div>

        <NextStepChoice encoded={encoded} />

        <p className="text-center text-sm text-slate-500 -mt-4">
          Your offer analysis is generated by AI using NLN's negotiation
          framework.
          {analysis.internalDataUsed &&
            " Market context includes anonymized data from offers previously analyzed by NLN."}
        </p>
      </main>
    </div>
  );
}

// Market-data sources the analysis was built on. Absent on results generated
// before sourcing existed, and empty when no usable data was found.
function SourceList({ sources }) {
  if (!Array.isArray(sources) || sources.length === 0) return null;

  return (
    <p className="text-sm text-slate-500 -mt-4">
      Market data sourced from{" "}
      {sources.map((s, i) => (
        <span key={`${s.url}-${i}`}>
          {i > 0 && (i === sources.length - 1 ? " and " : ", ")}
          <a
            href={s.url}
            target="_blank"
            rel="noopener noreferrer"
            title={s.note}
            className="font-medium text-navy-600 hover:text-navy-900 underline transition"
          >
            {s.name}
          </a>
        </span>
      ))}
      .
    </p>
  );
}

function NextStepChoice({ encoded }) {
  const navigate = useNavigate();

  function handleGetScript() {
    track("script_cta_clicked");
    // Proof/credibility step first; it stashes the offer data and sends
    // the visitor on to Stripe from there.
    navigate(`/proof${encoded ? `?d=${encoded}` : ""}`);
  }

  function handleBookSession() {
    track("session_cta_clicked");
    // Same pattern as the script path: sell the value on its own page
    // before handing off to the external booking link, rather than sending
    // people straight out of the app on the first click.
    navigate("/session");
  }

  return (
    <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-6 sm:p-8">
      <p className="font-serif font-semibold text-navy-900 text-xl text-center mb-6">
        What do you want next — a script you can run yourself, or a
        negotiator in your corner?
      </p>
      <div className="grid sm:grid-cols-2 gap-4">
        <button
          type="button"
          onClick={handleGetScript}
          className="rounded-lg bg-navy-900 hover:bg-navy-600 text-white p-5 text-center transition"
        >
          <span className="block font-semibold">Get my custom script</span>
          <span className="block text-sm text-navy-100 mt-1">
            A full counter-offer script written for your exact offer
          </span>
        </button>
        <button
          type="button"
          onClick={handleBookSession}
          className="rounded-lg border-2 border-navy-900 text-navy-900 hover:bg-navy-50 p-5 text-center transition"
        >
          <span className="block font-semibold">Book a Strategy Session</span>
          <span className="block text-sm text-slate-600 mt-1">
            Get a negotiator in your corner for the actual call
          </span>
        </button>
      </div>
    </div>
  );
}
